# This is a basic workflow to help you get started with Actions

name: python-run

# Controls when the action will run. Triggers the workflow on a cron schedule
on: |
  schedule:
    - cron: "20 0,2,12 * * *"
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: python pyfiles/updatejson.py

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        git config --global user.email "botdeep@email.id"
        git config --global user.name "BOT Rajdeep"
        git add .
        git commit -m "automated update"
        git push
